channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - cffi==1.15.1
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - lightning==2.1.3
  - matplotlib==3.7.1
  - numpy==1.24.3
  - packaging==23.1
  - pandas==2.2.1
  - pyyaml==6.0
  - torch==2.0.1
name: mlflow-env
