channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - tensorflow-intel==2.13.0
  - tensorflow==2.13.0
name: mlflow-env
