# Generated by Django 5.0.2 on 2024-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='groups',
            field=models.ManyToManyField(related_name='standard_users_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='standard_users_permissions', to='auth.permission'),
        ),
    ]
