# Generated by Django 5.0.2 on 2024-04-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_transaction_uploading_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='standarduser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='standarduser',
            name='job',
        ),
    ]
