# Generated by Django 5.0.2 on 2024-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
