# Generated by Django 5.0.2 on 2024-04-11 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_remove_standarduser_city_remove_standarduser_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend_api.transaction')),
            ],
            bases=('backend_api.transaction',),
        ),
    ]
