# Generated by Django 5.0.2 on 2024-03-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_standarduser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
