# Generated by Django 5.0.2 on 2024-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_transaction_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='accountType',
        ),
        migrations.AddField(
            model_name='standarduser',
            name='cc_num',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standarduser',
            name='city',
            field=models.CharField(default='Melbourne', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standarduser',
            name='dob',
            field=models.DateField(default='2024-03-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standarduser',
            name='job',
            field=models.CharField(default='Accountant', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transfer',
            field=models.CharField(max_length=100),
        ),
    ]
