# Generated by Django 5.0.2 on 2024-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_standarduser_accounttype_standarduser_cc_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
    ]
