# Generated by Django 5.0.2 on 2024-03-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='anomalous',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
